# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
canonifyURLs = true
baseURL = "https://cloudmindshub.github.io/workshop/"
publishDir = "docs"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "npnam.techii@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "AWS Account Setup"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> Cloudminds"
identifier = "Cloudminds"
url = "https://www.linkedin.com/company/105900568/admin/dashboard/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> FCJ AWS"
identifier = "FCJ_AWS"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 30

[Languages.vi]
title = "Thiết lập AWS Account"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> Cloudminds"
identifier = "AWS Study Group FB"
url = "https://www.linkedin.com/company/105900568/admin/dashboard/"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> FCJ AWS"
identifier = "FCJ_AWS"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 30
